src/Entity/Posts.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Exception;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PostsRepository")
 * @Vich\Uploadable
 */
class Posts
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var String|null
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     */
    private $image;


    /**
     * @var File|null
     * @Vich\UploadableField(mapping="posts_image", fileNameProperty="image")
     *
     */
    private $ImageFile;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Users", inversedBy="posts")
     * @ORM\JoinColumn(nullable=true)
     */
    private $user;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @Assert\Regex("/^[0-9]{5}$/")
     * @ORM\Column(type="string", length=255)
     */
    private $zipCode;

    /**
     * @ORM\Column(type="boolean", options={"default": false})
     */
    private $archive;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;


    public function __construct(){
        $this->created_at = new \DateTime();
        $this->updated_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getUser(): ?Users
    {
        return $this->user;
    }

    public function setUser(?Users $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getZipCode(): ?string
    {
        return $this->zipCode;
    }

    public function setZipCode(string $zipCode): self
    {
        $this->zipCode = $zipCode;

        return $this;
    }

    /**
     * @param File|null $ImageFile
     * @return Posts
     *
     */
    public function setImageFile(?File $ImageFile): Posts
    {
        $this->ImageFile = $ImageFile;
        if($this->ImageFile instanceof UploadedFile){
            $this->updated_at = new \DateTime('now');
        }
        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
        return $this->ImageFile;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getArchive()
    {
        return $this->archive;
    }

    /**
     * @param mixed $archive
     */
    public function setArchive($archive): void
    {
        $this->archive = $archive;
    }


}

src/Controller/UsersPostsController.php
<?php


namespace App\Controller;


use App\Entity\Posts;
use App\Entity\Users;
use App\Form\PostsType;
use App\Repository\PostsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\Security\Core\User\User;


/**
 * @Route("/user/my-post")
 */
class UsersPostsController extends AbstractController
{
//    /**
//     * @Route("/myposts", name="posts", methods={"GET"})
//     */
//    public function index(): Response
//    {
//        return $this->render('usersPosts/index.html.twig', [
////            'posts' => $postsRepository->findAll(),
//        ]);
//    }
    private $security;

    public function __construct(Security $security)
    {
        $this->security = $security;
    }


    /**
     * @Route("/new", name="my_new_post", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $post = new Posts();
        $form = $this->createForm(PostsType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $currentUser = $this->security->getUser();
            $post->setUser($currentUser);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($post);
            $entityManager->flush();
            $this->addFlash('success', "L'annonce a été créée");

            return $this->redirectToRoute('user_posts');
        }

        return $this->render('usersPosts/createPost.html.twig', [
            'post' => $post,
            'form' => $form->createView(),
        ]);
    }


    /**
     * @Route("/{id}/edit", name="edit_post", methods={"GET","POST"})
     */
    public function edit(Request $request, Posts $post): Response
    {
        $form = $this->createForm(PostsType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $this->addFlash('success', "L'annonce a été modifiée");

            return $this->redirectToRoute('user_posts');
        }

        return $this->render('usersPosts/editPost.html.twig', [
            'post' => $post,
            'form' => $form->createView(),
        ]);
    }

}

templates/usersPosts/createPost.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créer une annonce {% endblock %}

{% block body %}
    <div class="container mt-4 formContrainer">
        <h1 class="h1Style">Poster une annonce</h1>
        {#    {{ include('admin/posts/_form.html.twig') }}#}
        {{ form_start(form) }}
        {{ form_row(form.title) }}
        {{ form_row(form.description) }}
        {{ form_row(form.imageFile) }}
        {{ form_row(form.zipCode) }}
        {{ form_row(form.city) }}
        {{ form_widget(form.user, { 'attr': {'style': 'display:none'} }) }}
        <div class="text-right">
            <button class="btn btnSave">{{ button_label|default('Enregistrer') }}</button>
        </div>
        {{ form_end(form) }}
    </div>
{% endblock %}

{% block javascripts %}
    <script>
        $('.custom-file-input').on('change', function (event) {
            var inputFile = event.currentTarget;
            $(inputFile).parent()
                .find('.custom-file-label')
                .html(inputFile.files[0].name);
        });
    </script>
{% endblock %}

templates/usersPosts/editPost.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editer une annonce{% endblock %}

{% block body %}
    <div class="container mt-4 formContrainer">
        <div>
            <a class="btn btnBack" href="{{ path('user_posts') }}">Retour</a>
        </div>
        <h1 class="h1Style">Editer une annonce</h1>
        {{ form_start(form) }}
        {{ form_row(form.title) }}
        {{ form_row(form.description) }}
        {{ form_row(form.imageFile) }}
        {{ form_row(form.zipCode) }}
        {{ form_row(form.city) }}
{#        TODO : ne pas utiliser le form admin à cause du champ user ?#}
        {{ form_widget(form.user, { 'attr': {'style': 'display:none'} }) }}
        {{ form_row(form.archive) }}
        <div class="text-right">
            <button class="btn btnSave">{{ button_label|default('Enregistrer') }}</button>
        </div>
        {{ form_end(form) }}
    </div>
{% endblock %}

{% block javascripts %}
    <script>
        $('.custom-file-input').on('change', function (event) {
            var inputFile = event.currentTarget;
            $(inputFile).parent()
                .find('.custom-file-label')
                .html(inputFile.files[0].name);
        });
    </script>
{% endblock %}

templates/usersPosts/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}Mes annonces{% endblock %}


{% block body %}
    <div class="container mt-4">
        <h1 class="h1Style">Mes annonces</h1>
        {% for message in app.flashes('success') %}
            <div class="alert alert-success">{{ message }}</div>
        {% endfor %}
        {% for post in posts %}
            <div class="card text-center cardPost">
                <div class="card-header">
                    {{ post.title }}
                </div>
                <div class="card-body">
                    <h5 class="card-title"></h5>
                    <div class="card-text descCard">
                        {% if post.image %}
                            <img src="/images/posts/{{ post.image }}" alt="image" style="width: 10%">
                        {% endif %}
                        <p style="margin-left: 2em;}">{{ post.description }}
                        </p>
                    </div>
                    <a href="{{ path('edit_post', {id: post.id}) }}" class="btn btnEdit"
                       style="margin-top:2em">Modifier</a>
                </div>
                <div class="card-footer text-muted">
                    <span> Publié le {{ post.createdAt.date | date("d/m/Y H:i", "Europe/Paris") }}</span>
                </div>
            </div>
        {% else %}
            <p>Vous n'avez pas publié d'annonce</p>
        {% endfor %}
    </div>

{% endblock %}



{% block javascripts %}
    <script>
        $(document).ready(function () {
            setTimeout(function () {
                $('.alert-success').fadeOut()
            }, 3000);
        });
    </script>
{% endblock %}